name: CI CD Step 2

on:
  push:
    branches: ["main"]

jobs:
  linux-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check OS
        run: uname -a

      - name: Check disk
        run: df -h

      - name: Check memory
        run: free -
